### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nimasdj** [chriso/klein.php#274]
Hello,

1. Ability add filters just like Laravel router.
2. Ability to add custom validator in URI. e.g.
$klein->respond('GET', '/[:name]{customRegextfor :name}', function ($request, $response) {
would you consider this two features for me please?

Thanks,

**Comment by Rican7** [comment]
Hi! Thanks for requesting some features. A few things here:

- Something akin to filters will be arriving in Klein in the future. Until then, Klein uses a unique matching style which will execute all route matches (not just the first match that it finds). You can use that to your benefit here
- Custom regular expressions are available for routing by using the `@` character. [Check out the tests for some examples](https://github.com/chriso/klein.php/blob/5dc073f05adb67ee09680545b4cc7b0590d2559e/tests/Klein/Tests/RoutingTest.php#L484-L511)
- Shorthand methods have existed since Klein 2.0: https://github.com/chriso/klein.php/blob/5dc073f05adb67ee09680545b4cc7b0590d2559e/src/Klein/Klein.php#L1085-L1219

**Comment by nimasdj** [comment]
Thanks but for those requests that are already available, I have not seen much info in dics in official site.

**Comment by Rican7** [comment]
Yes, the docs could use some work. I'd be happy to take a pull request.
